"""Docker Compose exporter.

Maps architecture nodes to compose services. Service images are derived
from node type keys; the ``depends_on`` graph follows REST / database /
messaging edges so the generated stack is actually runnable.
"""

from app.schemas.common import Graph
from app.services.exporters.base import Exporter
from app.services.exporters.shared import FRAMEWORK_IMAGES, IMAGE_MAP


class DockerComposeExporter(Exporter):
    format = "docker"
    mime_type = "text/yaml"

    def export(self, graph: Graph, *, project_name: str) -> str:
        services: dict[str, dict[str, object]] = {}
        depends_on: dict[str, list[str]] = {}

        for node in graph.nodes:
            cfg = node.data.config
            framework = (cfg.framework or "").lower()
            image = IMAGE_MAP.get(node.data.type_key)
            if image is None:
                image = (
                    FRAMEWORK_IMAGES.get(framework, "node:20-alpine"),
                    "services",
                )
            image_name, _category = image

            service: dict[str, object] = {
                "image": image_name,
                "container_name": _slug(node.data.label),
                "restart": "unless-stopped",
            }

            if cfg.port:
                service["ports"] = [f"{cfg.port}:{cfg.port}"]
            if cfg.health_endpoint:
                service["healthcheck"] = {
                    "test": [
                        "CMD",
                        "wget",
                        "-qO-",
                        f"http://localhost:{cfg.port or 80}{cfg.health_endpoint}",
                    ],
                    "interval": "10s",
                    "timeout": "3s",
                    "retries": 3,
                }
            env = {var.key: var.value for var in cfg.env if var.key and not var.secret}
            if env:
                service["environment"] = env
            if cfg.replicas and cfg.replicas > 1:
                service["deploy"] = {"replicas": cfg.replicas}

            services[_slug(node.data.label)] = service

        # Build dependency graph from edges targeting infra nodes.
        for edge in graph.edges:
            source_label = _label_of(graph, edge.source)
            target_label = _label_of(graph, edge.target)
            if not source_label or not target_label or source_label == target_label:
                continue
            # Services depend on the infra they talk to; infra has no deps.
            if target_label in services:
                depends_on.setdefault(source_label, []).append(target_label)

        for name, deps in depends_on.items():
            if name in services:
                services[name]["depends_on"] = sorted(set(deps))

        lines = ["# Generated by FlowForge — edit at your own risk", "services:"]
        for name, service in services.items():
            lines.append(f"  {name}:")
            for key, value in service.items():
                lines.append(f"    {key}: {_yaml(value)}")
        return "\n".join(lines) + "\n"


def _label_of(graph: Graph, node_id: str) -> str:
    for node in graph.nodes:
        if node.id == node_id:
            return _slug(node.data.label)
    return ""


def _slug(label: str) -> str:
    slug = "".join(c if c.isalnum() else "-" for c in label.lower()).strip("-")
    return slug or "service"


def _yaml(value: object) -> str:
    if isinstance(value, dict):
        inner = ", ".join(f"{k}: {_yaml(v)}" for k, v in value.items())
        return "{" + inner + "}"
    if isinstance(value, list):
        return "[" + ", ".join(str(v) for v in value) + "]"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{value}"'
