"""Terraform exporter (HCL, Docker provider).

Generates a ``terraform apply``-ready module that recreates the diagram
as Docker containers on a shared network, with ``depends_on`` wiring
derived from the graph edges.
"""

from app.schemas.common import Graph
from app.services.exporters.base import Exporter
from app.services.exporters.shared import label_of, resolve_image, slug


class TerraformExporter(Exporter):
    format = "terraform"
    mime_type = "text/hcl"

    def export(self, graph: Graph, *, project_name: str) -> str:
        lines = [
            '# Generated by FlowForge - apply with "terraform apply"',
            "terraform {",
            "  required_providers {",
            "    docker = {",
            '      source  = "kreuzwerker/docker"',
            '      version = "~> 3.0"',
            "    }",
            "  }",
            "}",
            "",
            'provider "docker" {}',
            "",
            'resource "docker_network" "flowforge" {',
            f'  name = "{slug(project_name)}"',
            "}",
            "",
        ]

        # service → [infra targets it talks to]
        depends: dict[str, list[str]] = {}
        for edge in graph.edges:
            source = label_of(graph, edge.source)
            target = label_of(graph, edge.target)
            if source and target and source != target:
                depends.setdefault(source, []).append(target)

        for node in graph.nodes:
            cfg = node.data.config
            name = slug(node.data.label)

            lines.append(f'resource "docker_image" "{name}" {{')
            lines.append(f'  name = "{resolve_image(node)}"')
            lines.append("}")
            lines.append("")

            lines.append(f'resource "docker_container" "{name}" {{')
            lines.append(f'  name  = "{name}"')
            lines.append(f"  image = docker_image.{name}.image_id")
            lines.append('  restart = "unless-stopped"')
            lines.append("  networks_advanced {")
            lines.append("    name = docker_network.flowforge.name")
            lines.append("  }")
            if cfg.port:
                lines.append("  ports {")
                lines.append(f"    internal = {cfg.port}")
                lines.append(f"    external = {cfg.port}")
                lines.append("  }")
            env = [
                f"{var.key}={var.value}"
                for var in cfg.env
                if var.key and not var.secret
            ]
            if env:
                quoted = ", ".join(f'"{entry}"' for entry in env)
                lines.append(f"  env = [{quoted}]")
            deps = depends.get(name)
            if deps:
                refs = ", ".join(f"docker_container.{dep}" for dep in sorted(set(deps)))
                lines.append(f"  depends_on = [{refs}]")
            lines.append("}")
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"
