import {
	Network,
	ShieldCheck,
	Users,
	ShoppingCart,
	Boxes,
	CreditCard,
	Truck,
	Bell,
	Search,
	BarChart3,
	Sparkles,
	Database,
	Server,
	Leaf,
	Layers,
	Radio,
	Rabbit,
	Cpu,
	Waypoints,
	Activity,
	LineChart,
	ScrollText,
	Route,
	Flame,
	Cloud,
	Phone,
	Bot,
	Box,
	type LucideIcon,
} from "lucide-react";

/** Central registry so node/edge definitions can reference icons by string key. */
export const iconRegistry: Record<string, LucideIcon> = {
	network: Network,
	shield: ShieldCheck,
	users: Users,
	cart: ShoppingCart,
	boxes: Boxes,
	card: CreditCard,
	truck: Truck,
	bell: Bell,
	search: Search,
	chart: BarChart3,
	sparkles: Sparkles,
	database: Database,
	server: Server,
	leaf: Leaf,
	layers: Layers,
	radio: Radio,
	rabbit: Rabbit,
	cpu: Cpu,
	waypoints: Waypoints,
	activity: Activity,
	linechart: LineChart,
	logs: ScrollText,
	route: Route,
	flame: Flame,
	cloud: Cloud,
	phone: Phone,
	bot: Bot,
	box: Box,
};

export function getIcon(key: string): LucideIcon {
	return iconRegistry[key] ?? Box;
}
