"use client";

import { useState } from "react";
import { cn } from "@/lib/cn";
import { Reveal } from "./Reveal";

const tabs = [
  { id: "mermaid", label: "Mermaid", filename: "architecture.mmd" },
  { id: "compose", label: "Docker Compose", filename: "docker-compose.yml" },
  { id: "json", label: "JSON", filename: "architecture.json" },
] as const;

type TabId = (typeof tabs)[number]["id"];

export function ExportSection() {
  const [active, setActive] = useState<TabId>("mermaid");

  return (
    <section id="export" className="px-5 sm:px-8 py-20 sm:py-28 border-t border-[var(--border)]">
      <div className="mx-auto max-w-5xl">
        <Reveal className="max-w-xl">
          <span className="mono text-[11px] uppercase tracking-[0.14em] text-[var(--accent-strong)]">
            Export
          </span>
          <h2 className="mt-3 text-2xl sm:text-[2rem] font-semibold text-[var(--text-primary)]">
            The same architecture, in the format you need next
          </h2>
          <p className="mt-4 text-[15px] text-[var(--text-secondary)] leading-relaxed">
            No lock-in. Every canvas exports to formats your team already
            reads &mdash; drop them straight into a repo, a doc, or a design
            review.
          </p>
        </Reveal>

        <Reveal delay={0.1} className="mt-10">
          <div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--bg-raised)] overflow-hidden">
            <div className="flex items-center border-b border-[var(--border)] overflow-x-auto">
              {tabs.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setActive(t.id)}
                  className={cn(
                    "px-4 py-3 mono text-[12.5px] whitespace-nowrap border-b-2 -mb-px transition-colors",
                    active === t.id
                      ? "border-[var(--accent)] text-[var(--text-primary)]"
                      : "border-transparent text-[var(--text-tertiary)] hover:text-[var(--text-secondary)]"
                  )}
                >
                  {t.label}
                </button>
              ))}
            </div>
            <div className="px-3 py-2 border-b border-[var(--border)]">
              <span className="mono text-[11px] text-[var(--text-tertiary)]">
                {tabs.find((t) => t.id === active)?.filename}
              </span>
            </div>
            <div className="p-5 overflow-x-auto">
              {active === "mermaid" && <MermaidBlock />}
              {active === "compose" && <ComposeBlock />}
              {active === "json" && <JsonBlock />}
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

function Line({ children }: { children: React.ReactNode }) {
  return <div className="mono text-[12.5px] leading-relaxed whitespace-pre">{children}</div>;
}

const kw = "text-[var(--accent-strong)]";
const str = "text-[var(--sev-info)]";
const com = "text-[var(--text-tertiary)]";
const key = "text-[var(--text-secondary)]";
const val = "text-[var(--text-primary)]";

function MermaidBlock() {
  return (
    <div className="space-y-0.5">
      <Line><span className={com}>%% generated by FlowForge</span></Line>
      <Line><span className={kw}>graph</span> <span className={val}>LR</span></Line>
      <Line>  <span className={val}>client</span> {"-->"} <span className={val}>gateway</span></Line>
      <Line>  <span className={val}>gateway</span> {"-->"} <span className={val}>orders_api</span></Line>
      <Line>  <span className={val}>gateway</span> {"-->"} <span className={val}>users_api</span></Line>
      <Line>  <span className={val}>orders_api</span> {"-->"} <span className={val}>orders_db</span>[(<span className={str}>orders_db</span>)]</Line>
      <Line>  <span className={val}>users_api</span> {"-->"} <span className={val}>users_db</span>[(<span className={str}>users_db</span>)]</Line>
    </div>
  );
}

function ComposeBlock() {
  return (
    <div className="space-y-0.5">
      <Line><span className={key}>version:</span> <span className={str}>&quot;3.9&quot;</span></Line>
      <Line><span className={key}>services:</span></Line>
      <Line>  <span className={key}>orders-api:</span></Line>
      <Line>    <span className={key}>image:</span> <span className={str}>checkout/orders-api:latest</span></Line>
      <Line>    <span className={key}>depends_on:</span> [<span className={str}>orders_db</span>]</Line>
      <Line>    <span className={key}>environment:</span></Line>
      <Line>      <span className={key}>DATABASE_URL:</span> <span className={str}>postgres://orders_db:5432</span></Line>
      <Line>  <span className={key}>orders_db:</span></Line>
      <Line>    <span className={key}>image:</span> <span className={str}>postgres:16</span></Line>
    </div>
  );
}

function JsonBlock() {
  return (
    <div className="space-y-0.5">
      <Line>{"{"}</Line>
      <Line>  <span className={key}>&quot;nodes&quot;</span>: [</Line>
      <Line>    {"{"} <span className={key}>&quot;id&quot;</span>: <span className={str}>&quot;orders-api&quot;</span>, <span className={key}>&quot;type&quot;</span>: <span className={str}>&quot;service&quot;</span> {"}"},</Line>
      <Line>    {"{"} <span className={key}>&quot;id&quot;</span>: <span className={str}>&quot;orders_db&quot;</span>, <span className={key}>&quot;type&quot;</span>: <span className={str}>&quot;database&quot;</span> {"}"}</Line>
      <Line>  ],</Line>
      <Line>  <span className={key}>&quot;edges&quot;</span>: [</Line>
      <Line>    {"{"} <span className={key}>&quot;from&quot;</span>: <span className={str}>&quot;orders-api&quot;</span>, <span className={key}>&quot;to&quot;</span>: <span className={str}>&quot;orders_db&quot;</span> {"}"}</Line>
      <Line>  ]</Line>
      <Line>{"}"}</Line>
    </div>
  );
}
